/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as moMtokenSol from "./MOMtoken.sol";
export type { moMtokenSol };
export type { Exchange } from "./Exchange";
export type { PriceFeedConsumer } from "./PriceFeedConsumer";
