name: ci
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Build
    if: github.event.label.name == 'ready-to-merge'
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: 14
            registry-url: 'https://npm.pkg.github.com'
        - name: Git Identity
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Install dependencies
          run: npm install --global yarn && yarn install
        - name: Run lint
          run: yarn lint
        - name: Create new version
          run: yarn versionup
        - name: Commit version
          run: yarn commit-version


