name: ci
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Build
    if: github.event.label.name == 'ready-to-merge'
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: 14
            registry-url: 'https://npm.pkg.github.com'

        - name: Install dependencies
          run: npm install --global yarn && yarn install

        - name: Run lint
          run: yarn lint

        - name: Format code
          run: yarn format

        - name: Create new version and publish
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"
            
            yarn versionup
