on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v3
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 14
            cache: 'yarn'
            cache-dependency-path: 'yarn.lock'

        - name: Install dependencies
          run: npm install --global yarn && yarn install --frozen-lockfile

        - name: "Create version and publish "
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"
            yarn publish